/**
 * WP-H: машинные коды отказов при создании книги из утверждённого клиренса.
 *
 * До этого все отказы были голым текстом: фронт не мог отличить «интейк ещё не утверждён» от
 * «слаг занят» и показывал редактору английскую строку сервера. Коды добавляются аддитивно —
 * тексты сообщений сохранены, меняется только форма ответа (тело с `code` вместо строки).
 */
export const BOOK_CREATION_ERROR_CODES = {
  INTAKE_NOT_FOUND: 'BOOK_CREATION_INTAKE_NOT_FOUND',
  INTAKE_NOT_APPROVED: 'BOOK_CREATION_INTAKE_NOT_APPROVED',
  INTAKE_HAS_NO_APPROVED_REVIEW: 'BOOK_CREATION_INTAKE_HAS_NO_APPROVED_REVIEW',
  BOOK_ALREADY_CREATED: 'BOOK_CREATION_BOOK_ALREADY_CREATED',
  APPROVED_REVIEW_NOT_FOUND: 'BOOK_CREATION_APPROVED_REVIEW_NOT_FOUND',
  REVIEW_NOT_APPROVED: 'BOOK_CREATION_REVIEW_NOT_APPROVED',
  PROFILE_NOT_CURRENT: 'BOOK_CREATION_PROFILE_NOT_CURRENT',
  PROFILE_NOT_APPROVED: 'BOOK_CREATION_PROFILE_NOT_APPROVED',
  PROFILE_INTAKE_MISMATCH: 'BOOK_CREATION_PROFILE_INTAKE_MISMATCH',
  PUBLICATION_GATE_BLOCK: 'BOOK_CREATION_PUBLICATION_GATE_BLOCK',
  SLUG_TAKEN: 'BOOK_CREATION_SLUG_TAKEN',
  LANGUAGE_NOT_TARGETED: 'BOOK_CREATION_LANGUAGE_NOT_TARGETED',
  // WP-L.2: привязка клиренса к существующей книге.
  BOOK_NOT_FOUND: 'BOOK_CREATION_BOOK_NOT_FOUND',
  BOOK_ALREADY_UNDER_CLEARANCE: 'BOOK_CREATION_BOOK_ALREADY_UNDER_CLEARANCE',
  VERSIONS_NOT_ALLOWED_WHEN_ATTACHING: 'BOOK_CREATION_VERSIONS_NOT_ALLOWED_WHEN_ATTACHING',
  NO_VERSIONS_IN_TARGET_LANGUAGES: 'BOOK_CREATION_NO_VERSIONS_IN_TARGET_LANGUAGES',
} as const;

export type BookCreationErrorCode =
  (typeof BOOK_CREATION_ERROR_CODES)[keyof typeof BOOK_CREATION_ERROR_CODES];
