stages:
  - ci

ci:
  stage: ci
  image: node:22
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .yarn/cache/
      - node_modules/
  script:
    - yarn --version
    - yarn ci
  variables:
    CI: 'true'
    # Enable to run e2e in GitLab with a configured database
    CI_E2E: '0'
  only:
    - merge_requests
    - main
