import { existsSync, readFileSync } from 'node:fs';
import { EOL } from 'node:os';
import { join, resolve } from 'node:path';

/**
 * Сторож LEGACY-146: исключения линта живут только в блоке `ignores` файла `eslint.config.mjs`.
 *
 * Репозиторий на ESLint 9 с flat-конфигурацией. Такой конфиг читает исключения **только** из
 * поля `ignores` внутри `eslint.config.mjs`; корневой `.eslintignore` не читается вовсе, но
 * выглядит рабочим и до 26.08.2026 в корне лежал. Расхождение стоило трёх четвертей времени
 * каждого прогона: `libs/api-client/src/types.ts` — 102 КБ, сгенерированные
 * `openapi-typescript`, — проходили тип-зависимый линт в `scripts/ci.sh`, в `deploy.yml`
 * и в `pre-commit` через `lint-staged`. Замер 26.08.2026: `yarn lint` 109 с до правки,
 * 33 с после, набор предупреждений тот же.
 *
 * Отдельная ловушка: пути в `.eslintignore` были устаревшими. Он исключал
 * `libs/api-client/types.ts` (туда пишет `yarn openapi:types`, в гите такого файла нет)
 * и `libs/api-client/api-schema.json` (не существует), а линтовался
 * `libs/api-client/src/types.ts`. Буквальный перенос строк ничего бы не ускорил — отсюда
 * ожидание на оба пути сразу.
 *
 * Ловить это нечем: предупреждения по сгенерированному файлу ни на что не влияют (прогон идёт
 * без `--max-warnings=0`), лишние минуты списываются на `recommendedTypeChecked`, а сам
 * `.eslintignore` не читает ни `tsc`, ни `jest`, ни один шаг конвейера.
 */

const ROOT = resolve(__dirname, '..', '..');
const CONFIG = readFileSync(join(ROOT, 'eslint.config.mjs'), 'utf8');

/**
 * Пути из блока `ignores`. Строчные комментарии снимаются до разбора кавычек: комментарий
 * стоит над каждой группой, и апостроф внутри английского текста иначе съедает следующий
 * путь — эта спека на таком апострофе и покраснела при постройке.
 */
const ignoreEntries = (): string[] => {
  const block = /ignores:\s*\[([\s\S]*?)\]/.exec(CONFIG);
  if (block === null) {
    throw new Error('В eslint.config.mjs не найден блок ignores');
  }
  const withoutComments = block[1]
    .split(/\r?\n/)
    .filter((line) => !line.trim().startsWith('//'))
    .join(EOL);
  return [...withoutComments.matchAll(/'([^']+)'/g)].map((match) => match[1]);
};

describe('LEGACY-146: исключения линта', () => {
  it('корневой .eslintignore отсутствует — flat-конфиг его не читает', () => {
    expect(existsSync(join(ROOT, '.eslintignore'))).toBe(false);
  });

  it.each([
    ['libs/api-client/src/types.ts', 'версия в гите, её и линтовал прогон'],
    ['libs/api-client/types.ts', 'куда пишет yarn openapi:types'],
    ['libs/api-client/dist/**/*', 'сборка пакета'],
    ['libs/api-client/examples/**/*', 'примеры для потребителей'],
    ['dist/**/*', 'сборка сервиса'],
  ])('ignores содержит %s (%s)', (path) => {
    expect(ignoreEntries()).toContain(path);
  });

  /**
   * Отдельным случаем, потому что при ревью на нём разошлись два ревьюера. Файл рукописный,
   * и на вид исключать его из линта — потеря покрытия. Замер 26.08.2026 говорит обратное:
   * `tsconfig.eslint.json` включает весь каталог `scripts`, а `allowJs` нет ни в нём, ни в
   * `tsconfig.json`, поэтому `.js` в программу тип-зависимого линта не попадает вовсе.
   * Без этой строки `npx eslint scripts/generate-openapi-schema.js` — exit 1,
   * `Parsing error: "parserOptions.project" ... file was not found`; со строкой — exit 0.
   * `lint-staged` доносит до файла `eslint --fix` глобом `*.{ts,tsx,js}`, то есть отказ
   * прилетал бы на каждом коммите, который его трогает. Четыре директивы отключения правил
   * в шапке файла по той же причине мертвы — причина в `LEGACY-281`, здесь не чинится.
   * Решение арбитра 26.08.2026, `decisions-log.md`.
   */
  it('ignores содержит scripts/generate-openapi-schema.js — линт его не читает', () => {
    expect(ignoreEntries()).toContain('scripts/generate-openapi-schema.js');
  });

  it('сгенерированный types.ts действительно сгенерирован, а не написан руками', () => {
    const generated = join(ROOT, 'libs', 'api-client', 'src', 'types.ts');
    expect(existsSync(generated)).toBe(true);
    expect(readFileSync(generated, 'utf8').slice(0, 200)).toContain(
      'auto-generated by openapi-typescript',
    );
  });
});
