name: CI (portable)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Run portable CI script
        run: |
          yarn --version
          yarn ci
        env:
          CI: true
          # Set CI_E2E=1 and DATABASE_URL to enable e2e against an external DB.
          CI_E2E: '0'
